=== p3solutions/InfoArchive_AD-3.2_AutoBuild_v4-master/autobuild/demo/data/application/resources/xsd/template-content.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="content">
    <xs:complexType>
      <xs:sequence>
      	<xs:element name="dataset" maxOccurs="unbounded">
      		<xs:complexType>
      			<xs:sequence>
      				<xs:element name="name"/>
      			</xs:sequence>
      		</xs:complexType>
      	</xs:element>
        <xs:element name="hierarchy">
    		  <xs:complexType>
     			  <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="node" type="nodeType"/>
     			  </xs:sequence>
    		  </xs:complexType>
        </xs:element>
        <xs:element name="transformationConfigurations">
      		<xs:complexType>
			      <xs:sequence>
				      <xs:element name="transformationConfiguration" type="transformationConfigurationType" minOccurs="0" maxOccurs="unbounded"/>
			      </xs:sequence>
		      </xs:complexType>		
        </xs:element>    
        <xs:element name="searchConfigurations">
      		<xs:complexType>
			      <xs:sequence>
				      <xs:element name="searchConfiguration" type="searchConfigurationType" minOccurs="0" maxOccurs="unbounded"/>
			      </xs:sequence>
		      </xs:complexType>
        </xs:element>    
        <xs:element name="operationConfigurations">
      		<xs:complexType>
			      <xs:sequence>
				      <xs:element name="operationConfiguration" type="operationConfigurationType" minOccurs="0" maxOccurs="unbounded"/>
			      </xs:sequence>
		      </xs:complexType>
        </xs:element>    
      </xs:sequence>    
		</xs:complexType>		
  </xs:element>

  <xs:complexType name="nodeType">
  	<xs:sequence>
  		<xs:element name="id" type="non-empty-string"/>
  		<xs:element name="label" type="non-empty-string"/>
  		<xs:element name="icon" type="non-empty-string"/>
      <xs:element name="chainOfCustody" type="xs:boolean" minOccurs="0"/>
	  	<xs:element name="contentViewSettings" minOccurs="0">
     		<xs:complexType>
			    <xs:sequence>
				    <xs:element name="contentViewSetting" type="contentViewSettingType" minOccurs="0" maxOccurs="unbounded"/>
			    </xs:sequence>
		    </xs:complexType>
      </xs:element>
	  	<xs:element name="searchSettings" minOccurs="0">
     		<xs:complexType>
			    <xs:sequence>
				    <xs:element name="searchSetting" type="searchSettingType" minOccurs="0" maxOccurs="unbounded"/>
			    </xs:sequence>
		    </xs:complexType>
      </xs:element>
      <xs:element name="node" type="nodeType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
  </xs:complexType>

  <xs:complexType name="contentViewSettingType">
	  <xs:attribute name="refid" use="required" type="xs:IDREF"/>
	</xs:complexType>

	<xs:complexType name="searchSettingType">
		<xs:attribute name="refid" use="required" type="xs:IDREF"/>
    <xs:attribute name="name" use="required" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="transformationConfigurationType">
		<xs:all>
			<xs:element name="schemaIDs" type="xs:string"/>
			<xs:element name="styleURI" type="xs:string"/>
			<xs:element name="pdfExportStyleURI" type="xs:string" minOccurs="0"/>
			<xs:element name="pdfExportPipelineURI" type="xs:string" minOccurs="0"/>
			<xs:element name="exportPDFFromDatabase" type="xs:string" minOccurs="0"/>
			<xs:element name="exportSRCFromDatabase" type="xs:string" minOccurs="0"/>
			<xs:element name="pipelineURI" type="xs:string"/>
			<xs:element name="xquery" type="xs:string" />
      <xs:element name="contentType" type="xs:string" minOccurs="0"/>
      <xs:element name="fileName" type="xs:string" minOccurs="0"/>
			<xs:element name="pdf" type="xs:boolean"/>
		</xs:all>
		<xs:attribute name="id" use="required" type="xs:ID"/>
	</xs:complexType>

	<xs:complexType name="searchConfigurationType">
		<xs:sequence>
			<xs:element name="xformName" type="non-empty-string"/>
			<xs:element name="xquery" type="non-empty-string"/>
			<xs:element name="searchFields">
    		<xs:complexType>
		      <xs:sequence>
			      <xs:element name="searchFieldRow" maxOccurs="unbounded">
            	<xs:complexType>
		            <xs:sequence>
			            <xs:element name="searchField" type="searchFieldType" maxOccurs="unbounded"/>
                  <xs:element name="submitButton" minOccurs="0"/>
		            </xs:sequence>
	            </xs:complexType>
            </xs:element>   
		      </xs:sequence>
	      </xs:complexType>
	       </xs:element>   
				<xs:element name="searchResultItems" maxOccurs="unbounded">
	    		<xs:complexType>
			      <xs:sequence>
				      <xs:element name="searchResultItem" type="searchResultItemType" maxOccurs="unbounded"/>
			      </xs:sequence>
		      </xs:complexType>
	      </xs:element>   
	      <xs:element name="nestedSearches" minOccurs="0" maxOccurs="unbounded">
	      	<xs:complexType>
	          <xs:sequence>
	            <xs:element name="nestedSearch" type="nestedSearchType" minOccurs="0" maxOccurs="unbounded"/>
	          </xs:sequence>
	        </xs:complexType>
	      </xs:element>      
	      <xs:element name="reports" minOccurs="0">
	      	<xs:complexType>
	          <xs:sequence>
	            <xs:element name="report" type="reportType" minOccurs="0" maxOccurs="unbounded"/>
	          </xs:sequence>
	        </xs:complexType>
	      </xs:element>      
	      <xs:element name="operations" minOccurs="0">
	    		<xs:complexType>
			      <xs:sequence>
				      <xs:element name="operation" type="operationType" minOccurs="0" maxOccurs="unbounded"/>
			      </xs:sequence>
		      </xs:complexType>
	      </xs:element>
		  <xs:element name="crpWidth" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:ID"/>
	</xs:complexType>

	<xs:complexType name="searchFieldType">
		<xs:sequence>
			<xs:element name="name" type="non-empty-string"/>
			<xs:element name="label" type="non-empty-string"/>
			<xs:element name="type" type="non-empty-string" minOccurs="0"/>
     	<xs:element name="required" type="xs:boolean" minOccurs="0"/>
		<xs:choice minOccurs="0">
				<xs:element name="whereclauseparameter" type="non-empty-string"/>
				<xs:element name="flexiblecode" type="non-empty-string"/>
			</xs:choice>
     	<xs:element name="metadata" type="xs:boolean" minOccurs="0"/>
     	<xs:element name="fullText" type="xs:boolean" minOccurs="0"/>
     	<xs:element name="addAsVariable" type="xs:boolean" minOccurs="0"/>
      <xs:element name="suggestionsindex" type="non-empty-string" minOccurs="0"/>
      <xs:element name="indexPath" type="non-empty-string" minOccurs="0"/>
      <xs:element name="operator" type="non-empty-string" minOccurs="0"/>
      <xs:element name="options" minOccurs="0">
    		<xs:complexType>
		      <xs:sequence>
			      <xs:element name="option" type="optionType" maxOccurs="unbounded"/>
		      </xs:sequence>
          <xs:attribute name="type">
           <xs:simpleType>
            <xs:restriction base="xs:NCName">
             <xs:enumeration value="select"/>
             <xs:enumeration value="radio"/>
            </xs:restriction>
           </xs:simpleType>
          </xs:attribute>
	      </xs:complexType>
      </xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="searchResultItemType">
		<xs:all>
			<xs:element name="name" type="non-empty-string"/>
			<xs:element name="label" type="non-empty-string"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="nestedSearchType">
    <xs:sequence>
			<xs:element name="name" type="non-empty-string"/>
      <xs:group ref="nestedSearchGroup"/>
    </xs:sequence>
	</xs:complexType>

	<xs:complexType name="reportType">
    <xs:sequence>
      <xs:group ref="nestedSearchGroup"/>
      <xs:element name="xquery" type="non-empty-string" minOccurs="0"/>
    </xs:sequence>
		<xs:attribute name="id" use="required" type="xs:ID"/>
	</xs:complexType>

  <xs:group name="nestedSearchGroup">
		<xs:sequence>
			<xs:element name="label" type="non-empty-string"/>
			<xs:element name="description" type="xs:string"/>
      		<xs:element name="configurationId" type="non-empty-string"/>
			<xs:choice>
				<xs:sequence>
				<xs:element name="nodeId" type="non-empty-string"/>
				<xs:element name="fields" minOccurs="0">
    			<xs:complexType>
		      		<xs:sequence>
			      		<xs:element name="field" type="fieldType" maxOccurs="unbounded"/>
		      		</xs:sequence>
	      		</xs:complexType>
				</xs:element>
				</xs:sequence>
      			<xs:element name="transformationConfiguration"/>
			</xs:choice>
		</xs:sequence>
  </xs:group>

	<xs:complexType name="fieldType">
		<xs:all>
			<xs:element name="targetSearchFieldName" type="non-empty-string"/>
			<xs:element name="sourceResultItemName" type="non-empty-string"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="optionType">
		<xs:all>
			<xs:element name="name" type="non-empty-string"/>
			<xs:element name="label" type="non-empty-string"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="operationType">
    <xs:attribute name="refid" use="required" type="xs:IDREF"/>
	</xs:complexType>

	<xs:complexType name="operationConfigurationType">
		<xs:sequence>
      <xs:element name="xqueries" minOccurs="0">
    		<xs:complexType>
		      <xs:sequence>
			      <xs:element name="xquery" type="non-empty-string" maxOccurs="unbounded"/>
		      </xs:sequence>
	      </xs:complexType>
      </xs:element>
			<xs:element name="buttonLabel" type="non-empty-string"/>
      <xs:group ref="dialogGroup" minOccurs="0"/>
      <xs:element name="contentViewSetting" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:ID"/>
	</xs:complexType>

  <xs:group name="dialogGroup">
    <xs:sequence>
			<xs:element name="dialogTitle" type="non-empty-string"/>      
      <xs:choice>
        <xs:group ref="xformGroup"/>
        <xs:element name="message" type="non-empty-string"/>
      </xs:choice>
    </xs:sequence>
  </xs:group>


  <xs:group name="xformGroup">
    <xs:sequence>
  		<xs:element name="xformName" type="non-empty-string"/>
      <xs:element name="operationFields">
        <xs:complexType>
	  	    <xs:sequence>
		  	    <xs:element name="operationField" type="operationFieldType" maxOccurs="unbounded"/>
		      </xs:sequence>
	      </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>

	<xs:complexType name="operationFieldType">
		<xs:all>
			<xs:element name="name" type="non-empty-string"/>
			<xs:element name="label" type="non-empty-string"/>
			<xs:element name="type" type="non-empty-string" minOccurs="0"/>
     	<xs:element name="required" type="xs:boolean" minOccurs="0"/>
		</xs:all>
	</xs:complexType>

	<xs:simpleType name="non-empty-string">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== p3solutions/InfoArchive_AD-3.2_AutoBuild_v4-master/autobuild/demo/data/application/resources/template/template-content.xml
<?xml version="1.0" encoding="UTF-8"?>
<content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/template-content.xsd">
    <dataset>
    <name>application_dataset_name</name>
    </dataset>
    <dataset>
        <name>metadata</name>
    </dataset>
    <hierarchy>
    <title>DECOMM APPLICATION TITLE</title>
        
        <node>
      <id>parent_node_id</id>
      <label>PARENT NODE LABEL</label>
            <icon>allapplications16</icon>
            
            <node>
                <id>baseball</id>
                <label>Baseball</label>
                <icon>businessobject16</icon>
                <chainOfCustody>true</chainOfCustody>
                <contentViewSettings>
                    <contentViewSetting refid="playerDetails"/>
					<contentViewSetting refid="displayChainOfCustodyInfo"/>                    
                </contentViewSettings>
                <searchSettings>
                    <searchSetting name="Players" refid="searchPlayers"/>
                </searchSettings>
            </node>
            <node>
                <id>employee</id>
                <label>Employee Management</label>
                <icon>businessobject16</icon>
                <chainOfCustody>true</chainOfCustody>
                <contentViewSettings>
                    <contentViewSetting refid="employeeDetail"/>
                    <contentViewSetting refid="employeePayHistoryDetail"/>
                    <contentViewSetting refid="displayChainOfCustodyInfo"/>
                </contentViewSettings>
                <searchSettings>
                    <searchSetting name="Employee Search" refid="employeeSearch"/>
                    <searchSetting refid="employeePayrollDateSearch" name="Payroll Date Search"/>
                </searchSettings>
            </node>
            <node>
                <id>property</id>
                <label>Property Management</label>
                <icon>businessobject16</icon>
                <chainOfCustody>true</chainOfCustody>
                <contentViewSettings>
                    <contentViewSetting refid="propertyRentStreamDetail"/>
                    <contentViewSetting refid="propertyRentOptionsDetail"/>
                    <contentViewSetting refid="displayChainOfCustodyInfo"/>
                </contentViewSettings>
                <searchSettings>
                    <searchSetting name="Lease" refid="searchLeaseRentStream"/>
                    <searchSetting name="Options" refid="searchLeaseOptions"/>
                    <searchSetting name="Dynamic Columns" refid="searchLeaseDynamicColumns"/>
                </searchSettings>
            </node>
            <node>
                <id>reconciliation</id>
                <label>Reconciliation/Account Management</label>
                <icon>businessobject16</icon>
                <chainOfCustody>true</chainOfCustody>
                <contentViewSettings>
                    <contentViewSetting refid="generalLedgerDetails"/>
                    <contentViewSetting refid="subLedgerDetails"/>
                    <contentViewSetting refid="recDetails"/>
                    <contentViewSetting refid="historyDetails"/>
                    <contentViewSetting refid="accountDetails"/>
                    <contentViewSetting refid="displayChainOfCustodyInfo"/>
                </contentViewSettings>
                <searchSettings>
                    <searchSetting name="Reconciliation" refid="searchSVHarbor"/>
                    <searchSetting name="Account" refid="searchSVHarborAccount"/>
                </searchSettings>
            </node>
            <node>
                <id>sip</id>
                <label>SIP Check Data</label>
                <icon>businessobject16</icon>
                <chainOfCustody>false</chainOfCustody>
                <contentViewSettings>
                    <contentViewSetting refid="sipCheckDetails"/>
                </contentViewSettings>
                <searchSettings>
                    <searchSetting name="SIP Check Data" refid="searchSipCheck"/>
                </searchSettings>
            </node>
            <node>
                <id>acme</id>
                <label>Acme Retention Records</label>
                <icon>businessobject16</icon>
                <chainOfCustody>false</chainOfCustody>
                <contentViewSettings>
                    <contentViewSetting refid="AcmeRetentionPolicy"/>
                    <contentViewSetting refid="AcmeRecord"/>
                    <contentViewSetting refid="AcmeRetentionEvent"/>
                    <contentViewSetting refid="AcmeHold"/>
                </contentViewSettings>
                <searchSettings>
                    <searchSetting name="Records " refid="srchAcmeRecords"/>
                    <searchSetting name="Retention Policies" refid="srchAcmeRetentionPolicies"/>
                    <searchSetting name="Retention Events" refid="srchAcmeRetentionEvents"/>
                    <searchSetting name="Holds" refid="srchAcmeHolds"/>
                    <searchSetting name="Hold Records" refid="srchAcmeHoldRecords"/>
                </searchSettings>
            </node>
            <node>
                <id>auditlog</id>
                <label>Audit Logs</label>
                <icon>businessobject16</icon>
                <chainOfCustody>false</chainOfCustody>
                <contentViewSettings>
                    <contentViewSetting refid="auditLogDetails"/>
                </contentViewSettings>
                <searchSettings>
                    <searchSetting name="Audit Logs" refid="searchAuditLogs"/>
                </searchSettings>
            </node>
        </node>
    </hierarchy>
    
    <transformationConfigurations>
        
        
        <transformationConfiguration id="AcmeHold">
            <schemaIDs>AcmeHold</schemaIDs>
            <styleURI>dds://DOMAIN=resource/xslt/AcmeHold.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/displayxqueryresult.xpl</pipelineURI>
            <xquery>expand.xml</xquery>
            <pdf>false</pdf>
        </transformationConfiguration>
        
        <transformationConfiguration id="AcmeHoldRecords">
            <schemaIDs>AcmeHoldRecords</schemaIDs>
            <styleURI>dds://DOMAIN=resource/xslt/AcmeHoldRecords.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/displayxqueryresult.xpl</pipelineURI>
            <xquery>expand.xml</xquery>
            <pdf>false</pdf>
        </transformationConfiguration>
        
        <transformationConfiguration id="AcmeRetentionEvent">
            <schemaIDs>AcmeRetentionEvent</schemaIDs>
            <styleURI>dds://DOMAIN=resource/xslt/AcmeRetentionEvent.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/displayxqueryresult.xpl</pipelineURI>
            <xquery>expand.xml</xquery>
            <pdf>false</pdf>
        </transformationConfiguration>
        
        <transformationConfiguration id="AcmeRecord">
            <schemaIDs>AcmeRecord</schemaIDs>
            <styleURI>dds://DOMAIN=resource/xslt/AcmeRecord.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/displayxqueryresult.xpl</pipelineURI>
            <xquery>expand.xml</xquery>
            <pdf>false</pdf>
        </transformationConfiguration>
        <transformationConfiguration id="AcmeRetentionPolicy">
            <schemaIDs>AcmeRetentionPolicy</schemaIDs>
            <styleURI>dds://DOMAIN=resource/xslt/AcmeRetentionPolicy.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/displayxqueryresult.xpl</pipelineURI>
            
            <xquery>expand.xml</xquery>
            <pdf>false</pdf>
        </transformationConfiguration>
        
        
        <transformationConfiguration id="displayDefault">
            <schemaIDs/>
            <styleURI>dds://DOMAIN=resource/xslt/xml-verbatim.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/displayxqueryresult.xpl</pipelineURI>
            <xquery>expand.xml</xquery>
            <pdf>false</pdf>
        </transformationConfiguration>
        <transformationConfiguration id="displayURIDefault">
            <schemaIDs/>
            <styleURI>dds://DOMAIN=resource/xslt/xml-verbatim.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/display.xpl</pipelineURI>
            <xquery/>
            <pdf>false</pdf>
        </transformationConfiguration>
        <transformationConfiguration id="empty">
            <schemaIDs>empty.xsd</schemaIDs>
            <styleURI>dds://DOMAIN=resource/xslt/empty.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/display.xpl</pipelineURI>
            <xquery/>
            <pdf>false</pdf>
        </transformationConfiguration>
        <transformationConfiguration id="playerDetails">
            <schemaIDs>playerDetails</schemaIDs>
            <styleURI>dds://DOMAIN=resource/xslt/playerDetails.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/displayxqueryresult.xpl</pipelineURI>
            <xquery>expand.xml</xquery>
            <pdf>false</pdf>
        </transformationConfiguration>
        <!-- Employee Management -->
        <transformationConfiguration id="employeeDetail">
            <schemaIDs>employeeDetail</schemaIDs>
            <styleURI>dds://DOMAIN=resource/xslt/employeeDetail.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/displayxqueryresult.xpl</pipelineURI>
            <xquery>expand.xml</xquery>
            <pdf>false</pdf>
        </transformationConfiguration>
        <transformationConfiguration id="employeePayHistoryDetail">
            <schemaIDs>employeePayHistoryDetail</schemaIDs>
            <styleURI>dds://DOMAIN=resource/xslt/employeePayHistoryDetail.xsl</styleURI>
            <pipelineURI>dds://DOMAIN=resource/xproc/displayxqueryresult.xpl</pipelineURI>
            <xquery>expand.xml</xquery>
